export const tracks: any = [
  {
    id: '12oX2pkQ',
    url: 'https://www.chosic.com/wp-content/uploads/2021/07/The-Epic-Hero-Epic-Cinematic-Keys-of-Moon-Music.mp3',
    title: 'Keys of moon',
    artist: 'The Epic Hero',
    artwork: 'https://picsum.photos/id/1003/200/300',
    album: '',
    duration: 149,
    image: require('../../assets/images/trackimages/a.png'),
    category: ['kid'],
    type: ['stressreducer', 'performanceimprove'],
  },
  {
    id: '3UAL4arV',
    url: 'https://www.chosic.com/wp-content/uploads/2021/07/Raindrops-on-window-sill.mp3',
    title: 'Raindrops on ',
    artist: 'hu',
    artwork: 'https://picsum.photos/id/10/200/300',
    album: 'Chosic',
    duration: 119,
    image: require('../../assets/images/trackimages/b.png'),
    category: ['kid', 'fav'],
    type: ['bettersleep', 'performanceimprove'],
  },
  {
    id: 'U54wamfb',
    url: 'https://www.chosic.com/wp-content/uploads/2021/07/purrple-cat-equinox.mp3',
    title: 'Equinox',
    artist: 'Purple Cat',
    artwork: 'https://picsum.photos/id/1016/200/300',
    album: '',
    duration: 140,
    image: require('../../assets/images/trackimages/a.png'),
    category: ['kid', 'fav', 'anxious'],
    type: ['stressreducer', 'performanceimprove', 'bettersleep'],
  },
  {
    id: 'Kbiwfmzz',
    url: 'https://www.chosic.com/wp-content/uploads/2021/04/And-So-It-Begins-Inspired-By-Crush-Sometimes.mp3',
    title: 'And So It Begins',
    artist: 'New',
    artwork: 'https://picsum.photos/id/1019/200/300',
    album: 'Artificial Music',
    duration: 208,
    image: require('../../assets/images/trackimages/c.png'),
    category: ['kid', 'fav', 'anxious'],
    type: ['stressreducer', 'personalgrowth'],
  },
  {
    id: 'ZDDE5sqC',
    url: 'https://www.chosic.com/wp-content/uploads/2021/05/inossi-got-you.mp3',
    title: 'Got You',
    artist: 'First',
    artwork: 'https://picsum.photos/id/103/200/300',
    album: 'INOSSI',
    duration: 178,
    image: require('../../assets/images/trackimages/d.png'),
    category: ['fav', 'sleep'],
    type: ['stressreducer', 'anxityreduce', 'personalgrowth'],
  },
  {
    id: 'DRrWELVW',
    url: 'https://www.chosic.com/wp-content/uploads/2021/04/kvgarlic__largestreamoverloginforestmarch.mp3',
    title: 'Peaceful water stream',
    artist: 'Iser',
    artwork: 'https://picsum.photos/id/1038/200/300',
    album: 'Chosic',
    duration: 66,
    image: require('../../assets/images/trackimages/e.png'),
    category: ['anxious'],
    type: ['happinessincrease', 'performanceimprove', 'stressreducer'],
  },
];
